# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'esp32_cam.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ESP32_CAM(object):
    def setupUi(self, ESP32_CAM):
        ESP32_CAM.setObjectName("ESP32_CAM")
        ESP32_CAM.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ESP32_CAM)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startButton.sizePolicy().hasHeightForWidth())
        self.startButton.setSizePolicy(sizePolicy)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        self.stopButton.setCheckable(False)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout.addWidget(self.stopButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.videoDisplay = QtWidgets.QLabel(self.centralwidget)
        self.videoDisplay.setMinimumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.videoDisplay.setFont(font)
        self.videoDisplay.setStyleSheet("border:1px solid black;")
        self.videoDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.videoDisplay.setObjectName("videoDisplay")
        self.verticalLayout.addWidget(self.videoDisplay)
        self.statusLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.statusLabel.setFont(font)
        self.statusLabel.setStyleSheet("padding-left: 3px;")
        self.statusLabel.setObjectName("statusLabel")
        self.verticalLayout.addWidget(self.statusLabel)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 20)
        self.verticalLayout.setStretch(2, 1)
        ESP32_CAM.setCentralWidget(self.centralwidget)

        self.retranslateUi(ESP32_CAM)
        QtCore.QMetaObject.connectSlotsByName(ESP32_CAM)

    def retranslateUi(self, ESP32_CAM):
        _translate = QtCore.QCoreApplication.translate
        ESP32_CAM.setWindowTitle(_translate("ESP32_CAM", "ESP32_CAM"))
        self.lineEdit.setText(_translate("ESP32_CAM", "http://192.168.137.6:81/stream"))
        self.startButton.setText(_translate("ESP32_CAM", "开始"))
        self.stopButton.setText(_translate("ESP32_CAM", "停止"))
        self.videoDisplay.setText(_translate("ESP32_CAM", "请输入流地址并点击启动监控"))
        self.statusLabel.setText(_translate("ESP32_CAM", "未连接"))
